package us.dit.ass.primeraconsultaneurologica;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dolorNeuropatico implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("nivel del dolor")
	private Integer nivel;

	public dolorNeuropatico() {
	}

	public java.lang.Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(java.lang.Integer nivel) {
		this.nivel = nivel;
	}

	public dolorNeuropatico(java.lang.Integer nivel) {
		this.nivel = nivel;
	}

}